image: golang:1.11

variables:
  GOLANGCI_ARCHIVE: https://github.com/golangci/golangci-lint/releases/download/v1.11.2/golangci-lint-1.11.2-linux-amd64.tar.gz

stages:
  - lint

before_script:
  - go version
  - mkdir -p $GOPATH/src/lab.wtfteam.pro/wtfteam/
  - ln -s $(pwd) $GOPATH/src/lab.wtfteam.pro/wtfteam/lbtds
  - wget $GOLANGCI_ARCHIVE
  - tar xf *.tar.gz -C /usr/local/bin/
  - cd $GOPATH/src/lab.wtfteam.pro/wtfteam/lbtds

golangci:
  stage: lint
  script:
    - pwd
    - /usr/local/bin/golangci-lint run


