image: lab.wtfteam.pro:4567/containers/golangci-lint

stages:
  - lint
  - test

before_script:
  - go version
  - mkdir -p $GOPATH/src/lab.wtfteam.pro/wtfteam/
  - ln -s $(pwd) $GOPATH/src/lab.wtfteam.pro/wtfteam/lbtds
  - cd $GOPATH/src/lab.wtfteam.pro/wtfteam/lbtds

golangci:
  stage: lint
  script:
    - pwd
    - golangci-lint run

tests:
  stage: test
  script:
    - pwd
    - go test -test.v -cover `go list ./... | grep -v examples | grep -v internal`